name: Deploy Maintenance RoyalAquarium to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸš€ Deploy RoyalAquarium to VPS
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        known_hosts: ${{ secrets.VPS_KNOWN_HOSTS }}
        script: |
          cd /var/www/RAQ_maintanance_system

          git reset --hard HEAD
          git clean -fd
          git pull origin main --rebase

          cd backend
          npm ci
          pm2 restart booking_backend --update-env
          pm2 save

          cd ../frontend
          npm ci
          npm run build

          sudo systemctl reload nginx
